language: java
dist: trusty
script: gradle build
deploy:
  provider: releases
  api_key:
    secure: EduJhwYof0+sXKcHA0H6O92XYqZWgo2mDp03xnVMB1PWr9VUk/RNEbZ2fEO7Tess3L4gKqnwt3H3AHJy++DQfghQQXH0zIVP7dQWjxDxhvAoSUz2DMNAw8Y8q42eoNyUchltxo4Q/iQ+so4JtU57ZokKDGv3p5v7vmWyyhzozZP9drjBAyKs5763h31r262Akfp58ZBb3Db/7gVPpk9iJGK5Vb9rCCupl0SncSZtskkKpMougaq17nSXdC3CZB/F9N9kBxtX4i4coGKwL7Kf0TIHPaeyYnBW/+/2Uvpc4x+hjb+Vym9nAiitcoO/v+Ez3Yz4+vOkQG/gx35WeH9VdxzoI0lMcWmdIH4RvOdq15Oxi6ya0u7g5iT7jwXtAUSNBqrg8QRMee+/O39ApK7ul32Wqr9xeR8XtTKpqKuTTFx+slbWvD5NM4MhqXDeh5a9IP9n0BOFcK79sbcCnH5gZAFLlrGu5V7u2gBBjaFHeCqwg/I7vEr9AHTrYx25wtCsPiRzlGms+KzGdf7R0UGX/DDX/KXKpWnmITX7tBBe1i1Btc/vy1D9fLNb+HQaQCktrqzM44ZKSg9N5mva9uDjGv77lFrM2ErplbkDuZW8XgSZ6OQyQzwGjJvw5cN7GEXXY7wvISMn15lh2M8z//WmweVwvkfFeY/8cRzguOv4fxk=
  file_glob: true
  file: build/libs/casspoke*
  skip_cleanup: true
  on:
    tags: true
