app:
  tickRateInSec: 5
  httpServerPort: 8080

consul:
  host: consul01-par.central.criteo.preprod:8500
#  host: consul.service.consul
  port: 8500
  timeoutInSec: 10
  readConsistency: STALE
  refreshEveryMin: 1

service:
  type: CASSANDRA
  timeoutInSec: 60
  tags:
    - cluster=cstars04
    # - cassandra
