app:
  # A measurement should be taken every x seconds
  measurementPeriodInSec: 10
  # Discovery of the cluster should be re-done every x seconds (usefull if you use consul or teardown often clusters)
  refreshDiscoveryPeriodInSec: 60
  # Prometheus http server port endpoint
  httpServerPort: 8080

discovery:
  dns:
    - clustername: cstars01
      host: 10.50.4.55:9042
    - clustername: cstars02
      host: 10.50.4.55:9042
#  consul:
#    host: consul.service.consul
#    port: 8500
#    timeoutInSec: 10
#    readConsistency: STALE
#    tags:
#      - cluster=cstars01
#      #- cassandra

# Not usefull for now
service:
  type: CassandraRunner
  timeoutInSec: 60
