app:
  measurementPeriodInSec: 10
  refreshDiscoveryPeriodInSec: 60
  httpServerPort: 8080

consul:
  host: consul.service.consul
  port: 8500
  timeoutInSec: 10
  readConsistency: STALE

service:
  type: CassandraRunnerStats
  timeoutInSec: 60
  tags:
    - cluster=cstars04
    # - cassandra
