app:
  # A measurement should be taken every x seconds
  measurementPeriodInSec: 10
  # Operations timeout
  timeoutInSec: 60
  # Discovery of the cluster should be re-done every x seconds (useful if you use consul)
  refreshDiscoveryPeriodInSec: 600
  # Prometheus http server port endpoint
  httpServerPort: 8080

discovery:
  dns:
    - clustername: cstars01
      host: 127.0.0.1:9042
#  consul:
#    host: consul.service.consul
#    port: 8500
#    timeoutInSec: 10
#    readConsistency: STALE
#    tags:
#      - cluster=cstars01
#      #- cassandra
